import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ReduxProvider from "@/components/reduxWrapper/ReduxWrapper";
import ToastProvider from "@/components/toastProvider/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const raleway = Raleway({
  variable: "--font-raleway",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "JAHAANN EMS TEMPLATE",
  description: "Generated by Jahaann",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} antialiased bg-[#f7f7f7] dark:bg-gray-900`}
      >
        <ReduxProvider>
          <ThemeProvider
            enableSystem={true}
            attribute="class"
            defaultTheme="system"
          >
            {children}
            <ToastProvider />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
