import { Geist, Geist_Mono, Raleway, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ReduxProvider from "@/components/reduxWrapper/ReduxWrapper";
import ToastProvider from "@/components/toastProvider/ToastProvider";

const raleway = Raleway({
  variable: "--font-raleway",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "SURAJ COTTON MILLS",
  description: "Generated by Jahaann",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`  ${raleway.variable} ${inter.variable} antialiased bg-[#f7f7f7] dark:bg-gray-900`}
      >
        <ReduxProvider>
          <ThemeProvider
            enableSystem={true}
            attribute="class"
            defaultTheme="light"
          >
            {children}
            <ToastProvider />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
