import "./globals.css";
import { ThemeProvider } from "next-themes";
import ReduxProvider from "@/components/reduxWrapper/ReduxWrapper";
import ToastProvider from "@/components/toastProvider/ToastProvider";

export const metadata = {
  title: "SURAJ COTTON MILLS",
  description: "Generated by Jahaann",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`antialiased font-inter bg-[#f7f7f7]  dark:bg-gray-900`}>
        <ReduxProvider>
          <ThemeProvider
            enableSystem={true}
            attribute="class"
            defaultTheme="light"
          >
            {children}
            <ToastProvider />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
